language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.4.16
  - DJANGO=1.5.10
  - DJANGO=1.6.7
  - DJANGO=1.7

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO=1.7
        - python: "3.2"
          env: DJANGO=1.4.16
          env: DJANGO=1.5.10
        - python: "3.3"
          env: DJANGO=1.4.16
          env: DJANGO=1.5.10
        - python: "3.4"
          env: DJANGO=1.4.16
          env: DJANGO=1.5.10

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls

script:
  - coverage run runtests.py --source social_widgets

after_success:
  - coveralls