language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"

env:
  - DJANGO=1.6.7
  - DJANGO=1.7

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO=1.7

install:
  - pip install -q Django==$DJANGO
  - pip install coveralls

script:
  - coverage run runtests.py --source django-paginated-modelformset

after_success:
  - coveralls
